spring:
  application:
    name: currency-converter-service

  datasource:
    url: jdbc:h2:mem:testdb;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE;AUTO_RECONNECT=TRUE;MODE=MySQL;
    driver-class-name: org.h2.Driver
    username: sa
    password: password
  jpa:
    defer-datasource-initialization: true
    hibernate:
      ddl-auto: create

  h2:
    console:
      enabled: true
      path: /h2-console
      settings:
        trace: false
        web-admin-password: password
        web-allow-others: false

#  flyway:
#    enabled: true
#    baseline-on-migrate: true
#    schemas:
#      - currency_converter_service
#    sql-migration-suffixes:
#      - .sql


#  autoconfigure:
#    exclude:
#        - org.springframework.boot.autoconfigure.orm.jpa.HibernateJpaAutoConfiguration
server:
  address: localhost
  port: 8091

management:
  endpoints:
    web:
      exposure:
        include: '*'
