spring:
  application:
    name: currency-converter-service

  datasource:
    url: jdbc:mysql://localhost:3306/currency_converter_service?useSSL=false&allowPublicKeyRetrieval=true
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: currency
    password: currency_password
  jpa:
    hibernate:
      ddl-auto: none

  liquibase:
    change-log: classpath:db/changelog/master_changelog.yml

server:
  address: localhost
  port: 8091

management:
  endpoints:
    web:
      exposure:
        include: '*'
