spring:
  application:
    name: currency-converter-service

  datasource:
    url: jdbc:h2:mem:testdb;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE;AUTO_RECONNECT=TRUE;MODE=MySQL;
    driver-class-name: org.h2.Driver
    username: sa
    password: password
  jpa:
#    defer-datasource-initialization: true
    hibernate:
      ddl-auto: create

  h2:
    console:
      enabled: true
      path: /h2-console
      settings:
        trace: false
        web-admin-password: password

  liquibase:
    change-log: classpath:db/changelog/master_changelog.yml

server:
  address: localhost
  port: 8091

management:
  endpoints:
    web:
      exposure:
        include: '*'
