spring:
  application:
    name: currency-converter-service

  datasource:
    url: jdbc:mysql://localhost:3306/currency_converter_service?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: currency
    password: currency_password
  jpa:
    hibernate:
      ddl-auto: none

  liquibase:
    change-log: classpath:db/changelog/master_changelog.yml

  quartz:
    job-store-type: memory
    scheduler-name: ExchangeRateScheduler
    overwrite-existing-jobs: true
    auto-startup: true

server:
  address: localhost
  port: 8091

management:
  endpoints:
    web:
      exposure:
        include: '*'

app:
  config:
    exchange-rate-api-url: https://v6.exchangerate-api.com/v6
    quartz-scheduler-enabled: false